FROM golang:1.27-bookworm AS build
RUN mkdir -p /out \
    && CGO_ENABLED=0 GOBIN=/out go install github.com/pressly/goose/v3/cmd/goose@v3.28.0

FROM alpine:3.24
RUN apk --no-cache add ca-certificates
COPY --from=build /out/goose /usr/local/bin/goose
COPY internal/db/migrations /migrations
USER 65532:65532
ENTRYPOINT ["goose"]
