// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateMessage(ctx context.Context, text string) error
	GetMessages(ctx context.Context) ([]Message, error)
}

var _ Querier = (*Queries)(nil)
